import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useState } from 'react'

import { AnswersContext } from './_app'

import Answer from 'components/Answer'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [answers, setAnswers] = useContext(AnswersContext)
  const [isQuestion, setIsQuestion] = useState(true)
  const [question, setQuestion] = useState("")

  const onAddPoll = ()=>{
    console.log(`Question: ${question}`)
  }

  const onAddAnswer = (newAnswer: string)=>{
    answers.pop()
    setAnswers([...answers, newAnswer, ""])
  }

  const allAnswers = answers.map((answer, index)=><Answer key={index} {...{answer, question, onAddAnswer}}  />)

  return (
    <>
      <Head>
        <title>Pollster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isQuestion && <h3>{question} </h3>}
      <div className={styles.form}>
        {isQuestion ? <div className={styles.form_input}>
          <input type="text" name="question" id="question" className={styles.form_input_box} required value={question} onChange={({currentTarget:{value}})=>setQuestion(value)} onKeyDown={(e)=>{
            if(e.key === "Enter") setIsQuestion(false)
            
          }} />
          <label className={styles.form_input_label} htmlFor="question">Question</label>
        </div> : allAnswers}
        {!isQuestion && 
        <div className={styles.form_action}>
          <button className={`${styles.form_action_btn} ${styles.form_action_backBtn}`} onClick={()=>setIsQuestion(true)}>Retour</button>
          <button className={`${styles.form_action_btn} ${styles.form_action_createBtn}`} type="submit">Create Poll</button>
        </div>}
      </div>
    </>
  )
}

export default Home
